POST http://localhost:5000/api/phones
Content-Type: application/json

{
  "name": "Pro 10",
  "brand": "Samsung",
  "price": 10000
}

//validation error
POST http://localhost:5000/api/phones
Content-Type: application/json

{
  "name": "Pro 10",
  "brand": "Samsung1",
  "price": 10000
}

GET http://localhost:5000/api/phones

GET http://localhost:5000/api/phones/6450e325200255d506643567

PATCH http://localhost:5000/api/phones/6450e325200255d506643567
Content-Type: application/json

{
  "name": "Pro 11"
}

//validation error
PATCH http://localhost:5000/api/phones/6450e325200255d506643567
Content-Type: application/json

{
  "name": "a",
  "brand":"b"
}

DELETE http://localhost:5000/api/phones/6450e325200255d506643567

POST http://localhost:5000/api/users/644e752688e5378fba6f27c0/phones
Content-Type: application/json

{
  "name":"Pro",
  "brand":"Samsung",
  "price": 50000
}

//validation error
POST http://localhost:5000/api/users/644e752688e5378fba6f27c0/phones
Content-Type: application/json

{
  "name":"Pro",
  "brand":"ChinChun",
  "price": 50000
}

GET http://localhost:5000/api/users/644e752688e5378fba6f27c0/phones

//invalid user
GET http://localhost:5000/api/users/644e752688e5378fba6f27c1/phones
